### ISSUE TITLE
Error when performing `syncAddressBook` against Google Cardav

### ISSUE THREAD

**Issue by arcturus** [gaye/dav#87]
Once you have a valid account against google cardav server and perform the following command:

```
dav.syncAddressBook(account).then(function(result) {
  console.log('Result: ', result);
}, function(error) {
  console.log('Error: ', err);
}
```

The output is:
`Error:  [TypeError: Cannot read property 'send' of undefined]`

**Comment by arcturus** [comment]
Full output with debug enabled:

```
[dav:webdav] basic sync.
[dav:webdav] Missing ctag.
[dav:contacts] ctag changed so we need to fetch stuffs.
Error:  [TypeError: Cannot read property 'credentials' of undefined]
```

**Comment by gaye** [comment]
Thanks @arcturus. I'll take a look tomorrow!

**Comment by gaye** [comment]
@arcturus So this https://gist.github.com/gaye/81b23148e3b9b827f78f actually works for me. There are two issues. One is that you're calling `syncAddressBook` with the account instead of the `account.addressBooks[0]` or something similar. Another one is that `syncAddressBook` needs a transport (like `dav.transport.OAuth2`). To get around this, you can use the `dav.Client` interface for your requests like I did in my example. The idea of the client is that you give it a transport and then you can call methods on it and it will default to using that transport for all of the requests. Makes sense?
